#!/usr/bin/env bash

######################################################################
# @author      : drossos
# @file        : .backtick_local_linux
# @created     : Wednesday Jul 15, 2020 14:38:07 EEST
#
# @description : Script to querying available resources, used with 
# 			     `backtick` command of GNU Screen.
######################################################################

# Get top info 
top_info=$(top -bn 1)

# Get memory info
mem_info=$(free -k | sed -n 2p | tr -s ' ')

# Get used and total memory
mem_avail=$(echo "$mem_info" | cut -d ' ' -f 7)
mem_tot=$(echo "$mem_info" | cut -d ' ' -f 2)
mem_used=$((mem_tot - mem_avail))

# Calc percentage
cpu_mem=$(echo "(100/$mem_tot) * $mem_used" | bc -l | awk '{print ($0-int($0)<0.499)?int($0):int($0)+1}')

# Get CPU utilization
cpu_util=$(echo "$top_info" | sed -n 3p | tr -s ' ' | cut -d ' ' -f 8)
cpu_util=$(echo $cpu_util | awk '{print ($0-int($0)<0.499)?int($0):int($0)+1}')
cpu_util=$(echo "100 - $cpu_util" | bc )

# Get GPU utilization
gpu_info=$(nvidia-smi -q -d UTILIZATION)
gpu_util=$(echo "$gpu_info" | sed -n 11p | tr -s ' ' | cut -d ' ' -f 4)
gpu_mem=$(echo "$gpu_info" | sed -n 12p | tr -s ' ' | cut -d ' ' -f 4)

# Make values to be 2 digits
printf -v cpu_util "%02d" "$cpu_util"
printf -v cpu_mem "%02d" "$cpu_mem"
printf -v gpu_util "%02d" "$gpu_util"
printf -v gpu_mem "%02d" "$gpu_mem"

printf -v cpu_util "%3s" "$cpu_util"
printf -v cpu_mem "%3s" "$cpu_mem"
printf -v gpu_util "%3s" "$gpu_util"
printf -v gpu_mem "%3s" "$gpu_mem"

# Echo the resulting string
echo "CPU util/mem: "$cpu_util"%/"$cpu_mem"% | GPU util/mem: "$gpu_util"%/"$gpu_mem"%"
# EOF
