#!/bin/bash
#
len_thr=49
current_song=$(osascript ~/.myscreen_files/currently_playing.scpt)

if [ -z ${current_song:0:1} ]
then
    current_song=${current_song:1:$((${#current_song}-1))}
fi

if [ -z $current_song ]
then
	to_return='Nothing is playing'
else
	to_return="Now playing: ""$current_song"
	if [ "${#to_return}" -gt $len_thr ]
	then
		to_return=${to_return:0:$(($len_thr-3))}"..."
	fi
fi

printf -v to_return "%-$len_thr.$len_thr""s" "$to_return"
echo "$to_return"
# EOF
